### ISSUE TITLE
awesome-pages not working

### ISSUE THREAD

**Issue by ionetiq-mike** [lukasgeiter/mkdocs-awesome-pages-plugin#110]
Hi

I'm new to mkdocs but found this plug-in. Seems easy to follow but it simply isn't working. When I edit the mkdocs.yaml in VSCode I'm getting an error for the plugin line:

![image](https://github.com/user-attachments/assets/78b0fe4c-c35e-4e74-b314-c49d7fdbe8bb)

![image](https://github.com/user-attachments/assets/eedf88c1-0529-4da3-970c-924f6829eacc)

my .pages file in the docs subdirectory is:

nav:
    - index.md
    - Installation.md
    - Service Layer.md
    - Application.md
    - StandardWidgets.md
    - WorkView.md
    - BasicViewer.md
    - FlexQuery.md
    - Create Account.md
    - Forgot Password.md
    - General concepts.md
    - Gateway Styling.md
    - Localisation.md

I'm sure I'm making a silly mistake but would appreciate any assistance to get up and running

Thanks
Mike

**Comment by ionetiq-mike** [comment]
Thanks for the help!  Guess I'll just go find an alternative

**Comment by kamilkrzyskow** [comment]
Hello, I'm not the maintainer, but stumbled on this notification.
The error inside VS Code is a schema error, not a compilation issue, there is not enough information to follow up on this to know what doesn't work.

- https://squidfunk.github.io/mkdocs-material/schema.json
The schema from the Material theme doesn't include `awesome-pages`, not sure if this only needs a one line fix or if this plugin would need to maintain their own schema and hook it up to the Material theme schema. But again this is only a "linting" level issue and should have no say in how MkDocs runs.

What happens when you run `mkdocs serve`? If the plugin is not installed and not detected by MkDocs then it would crash with a missing plugin error. Good practice when asking for help would be to provide a runnable reproducible minimal example, which is typically a requirement over at the Material theme:
- https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/

**Comment by ionetiq-mike** [comment]
Thank you for taking the time to answer Kamil.  Very good advice that I note and will take a look at but in this case the delay in any response and assistance has made me look elsewhere.

**Comment by lukasgeiter** [comment]
Hi @ionetiq-mike, apologies for not responding to your issue earlier. As @kamilkrzyskow points out, it's a linting error and running `mkdocs serve` should show that the plugin still works.

Of course, whether you use my plugin or not is entirely up to you.
